# Generated by Django 4.1.3 on 2022-12-02 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thing',
            old_name='descriptiom',
            new_name='description',
        ),
    ]
